version: '3'
services:
  postgresdb:
    build:
      context: ../rec-service/test_db/
      dockerfile: Dockerfile
    #image: "postgres-db"
    environment:
       POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"       
  recserver:
    build:
      context: ../rec-service/service
      dockerfile: Dockerfile
    # image: rec-server
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    ports:
      - "5000:5000"
    depends_on:
       - postgresdb
    # volumes:
    #   - .:/app
  webdemo:
    build:
      context: .
      dockerfile: Dockerfile
    # image: rec-server
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    ports:
      - "5002:5002"
    depends_on:
       - postgresdb
       - recserver
