version: '3'
services:
  postgresdb:
    build:
      context: ../rec-service/test_db/
      dockerfile: Dockerfile
    environment:
       POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"       
  recserver:
    build:
      context: ../rec-service/service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
       - postgresdb
  webdemo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
       - postgresdb
       - recserver